### ISSUE TITLE
Ubuntu ./bin/install.sh

### ISSUE THREAD

**Issue by mribbons** [socketsupply/socket#196]
### What OS are you using (`uname -a`, or Windows version)?
Linux test-socket-ubu-22 5.19.0-32-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jan 30 17:03:34 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### What programming language are you using (C/C++/Go/Rust)?

gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### What did you expect to see and what you saw instead?

4671a8cc2284cc1a9d6d28db45ad903f45b1d3e2

Running
```bash
./bin/install.sh
```
Install failed, had to add the following packages manually:
```
sudo apt install autoconf pkg-config libtool libwebkit2gtk-4.1-dev -y
```

`libtool` and `libwebkit2gtk-4.1-dev` weren't identified as missing by `install.sh`

I suggest adding this as a 1 liner rather than advising each individual missing package.

Also if the install fails due to missing tools, libuv build isn't reattempted on subsequent runs unless `build` is `rm -rf`d.

~~The installation is still failing due to other issues, will discuss on discord.~~
Build now works using:
```
sudo apt install clang
```
Looks like g++ isn't supported.

**Comment by chicoxyzzy** [comment]
Is it fixed now?

**Comment by mribbons** [comment]
@chicoxyzzy I think some of this is still relevant, the build deps should be installed on prompt rather than advising the user one at a time and forcing them to restart the script over and over.

> libtool and libwebkit2gtk-4.1-dev weren't identified as missing by install.sh

This is fixed.

**Comment by lamiazar** [comment]
> some of this is still relevant
 
I tested this on `ubuntu 22` a few weeks ago and yes this is still an issue.

**Comment by lamiazar** [comment]
I tested this on a fresh VM: 
![ubuntuuu](https://github.com/socketsupply/socket/assets/79177582/3410a344-0bdd-499d-b06a-028fdad082df)


```
./bin/install.sh
warn - using '/home/mia/.local/share/socket' as SOCKET_HOME
warn - Installing to '/usr/local'
# Determining default Android search paths.
ok - ANDROID_HOME, JAVA_HOME, and GRADLE_HOME search paths configured.
# Determining Android paths.
Do you want to install Android build dependencies?
Download size: 5.5GB, Installed size: 12.0GB [y/N]
> n
warn - You have elected to not install Android dependencies.
warn - You can use 'export NO_ANDROID=1' to avoid this prompt in the future.
# preparing directories...
ok - directories prepared
# building libuv for desktop (x86_64) on Linux...
ok - built libuv for desktop (x86_64)
ok - copied headers
# building runtime library
Package webkit2gtk-4.1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `webkit2gtk-4.1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'webkit2gtk-4.1' found
# building runtime static libary (x86_64-desktop)
# compiling object (x86_64-desktop) app.cc
# compiling object (x86_64-desktop) bluetooth.cc
# compiling object (x86_64-desktop) core.cc
# compiling object (x86_64-desktop) javascript.cc
# compiling object (x86_64-desktop) peer.cc
# compiling object (x86_64-desktop) fs.cc
# compiling object (x86_64-desktop) bridge.cc
# compiling object (x86_64-desktop) context.cc
# compiling object (x86_64-desktop) udp.cc
# compiling object (x86_64-desktop) ipc.cc
# compiling object (x86_64-desktop) extension.cc
# compiling object (x86_64-desktop) javascript.cc
# compiling object (x86_64-desktop) ipc.cc
# compiling object (x86_64-desktop) env.cc
# compiling object (x86_64-desktop) json.cc
# compiling object (x86_64-desktop) linux.cc
# compiling object (x86_64-desktop) process.cc
/home/mia/socket/build/x86_64-desktop/app/app.o not built..
arch: x86_64
# precompiling main program for desktop
# building cli for desktop (x86_64)...
Package webkit2gtk-4.1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `webkit2gtk-4.1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'webkit2gtk-4.1' found
Package webkit2gtk-4.1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `webkit2gtk-4.1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'webkit2gtk-4.1' found
not ok - unable to build. See trouble shooting guide in the README.md file:\n/usr/lib/llvm-12/bin/clang++ -Wno-unused-command-line-argument - please report (https://discord.gg/YPV32gKCsH)
not ok - unable to build. See trouble shooting guide in the README.md file - please report (https://discord.gg/YPV32gKCsH)
```

**Comment by jwerle** [comment]
> I tested this on a fresh VM: ![ubuntuuu](https://user-images.githubusercontent.com/79177582/262907576-3410a344-0bdd-499d-b06a-028fdad082df.png)
> 
> ```
> ./bin/install.sh
> warn - using '/home/mia/.local/share/socket' as SOCKET_HOME
> warn - Installing to '/usr/local'
> # Determining default Android search paths.
> ok - ANDROID_HOME, JAVA_HOME, and GRADLE_HOME search paths configured.
> # Determining Android paths.
> Do you want to install Android build dependencies?
> Download size: 5.5GB, Installed size: 12.0GB [y/N]
> > n
> warn - You have elected to not install Android dependencies.
> warn - You can use 'export NO_ANDROID=1' to avoid this prompt in the future.
> # preparing directories...
> ok - directories prepared
> # building libuv for desktop (x86_64) on Linux...
> ok - built libuv for desktop (x86_64)
> ok - copied headers
> # building runtime library
> Package webkit2gtk-4.1 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `webkit2gtk-4.1.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'webkit2gtk-4.1' found
> # building runtime static libary (x86_64-desktop)
> # compiling object (x86_64-desktop) app.cc
> # compiling object (x86_64-desktop) bluetooth.cc
> # compiling object (x86_64-desktop) core.cc
> # compiling object (x86_64-desktop) javascript.cc
> # compiling object (x86_64-desktop) peer.cc
> # compiling object (x86_64-desktop) fs.cc
> # compiling object (x86_64-desktop) bridge.cc
> # compiling object (x86_64-desktop) context.cc
> # compiling object (x86_64-desktop) udp.cc
> # compiling object (x86_64-desktop) ipc.cc
> # compiling object (x86_64-desktop) extension.cc
> # compiling object (x86_64-desktop) javascript.cc
> # compiling object (x86_64-desktop) ipc.cc
> # compiling object (x86_64-desktop) env.cc
> # compiling object (x86_64-desktop) json.cc
> # compiling object (x86_64-desktop) linux.cc
> # compiling object (x86_64-desktop) process.cc
> /home/mia/socket/build/x86_64-desktop/app/app.o not built..
> arch: x86_64
> # precompiling main program for desktop
> # building cli for desktop (x86_64)...
> Package webkit2gtk-4.1 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `webkit2gtk-4.1.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'webkit2gtk-4.1' found
> Package webkit2gtk-4.1 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `webkit2gtk-4.1.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'webkit2gtk-4.1' found
> not ok - unable to build. See trouble shooting guide in the README.md file:\n/usr/lib/llvm-12/bin/clang++ -Wno-unused-command-line-argument - please report (https://discord.gg/YPV32gKCsH)
> not ok - unable to build. See trouble shooting guide in the README.md file - please report (https://discord.gg/YPV32gKCsH)
> ```

this occurred after installing `webkit2gtk4.1` ?

**Comment by lamiazar** [comment]
>  this occurred after installing webkit2gtk4.1 ?

I didn't install it, I just run`./bin/install.sh` on fresh VM, I was trying to reproduce this:
```
Install failed, had to add the following packages manually:
sudo apt install autoconf pkg-config libtool libwebkit2gtk-4.1-dev -y
```
